In [72]:
import torch
import numpy as np

In [73]:
x=torch.rand(3)

In [74]:
print(x)

tensor([0.0345, 0.1159, 0.3205])


In [75]:

print(torch.cuda.current_device())


AssertionError: Torch not compiled with CUDA enabled

In [76]:
torch.cuda.is_available()

False

# Empty-function that creates a tensor with unitialised values

In [16]:
x=torch.empty(1,3)
print(x)

tensor([[0., 0., 0.]])


# Random values Initialisation

In [17]:
x=torch.rand(2,2)
print(x)

tensor([[0.8799, 0.6884],
        [0.3084, 0.8317]])


# Initialisation with ones

In [19]:
x=torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


# Data-types

In [25]:
#torch.float16, torch.integer, torch.double
print(x.dtype)

torch.float32


# Size

In [26]:
print(x.size())

torch.Size([2, 2])


# Tensors with initialised values

In [28]:
x=torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


# Pytorch Operations

In [33]:
x=torch.rand(2,2)
y=torch.rand(2,2)

In [34]:
print(x)
print(y)

tensor([[0.2321, 0.7322],
        [0.2126, 0.7186]])
tensor([[0.8398, 0.4191],
        [0.9864, 0.7815]])


In [40]:
#Addition
z=x+y
z=torch.add(x,y)
y.add_(x)
print(z)

tensor([[1.5360, 2.6157],
        [1.6243, 2.9374]])


In pytorch, every function what has trailing _ does an implace operation

In [42]:
#division
p=x/y
p=torch.div(x,y)
print(p)

tensor([[0.1511, 0.2799],
        [0.1309, 0.2447]])


# Slicing

In [44]:
a=torch.rand(5,3)
print(a)

tensor([[0.6378, 0.8520, 0.0040],
        [0.7556, 0.1214, 0.8729],
        [0.8409, 0.5430, 0.1014],
        [0.9507, 0.2949, 0.9161],
        [0.5338, 0.6740, 0.6426]])


In [46]:
print(a[1,:])

tensor([0.7556, 0.1214, 0.8729])


In [49]:
#When we have only 1 value as form of tensor then to get exact value, we can use a .item() method
print(a[1,1])
print(a[1,1].item())

tensor(0.1214)
0.12138283252716064


# Reshaping

In [51]:
b=torch.rand(4,4)
print(b)

tensor([[0.6276, 0.9930, 0.2717, 0.6213],
        [0.5980, 0.1673, 0.1510, 0.6388],
        [0.1697, 0.8272, 0.5762, 0.1804],
        [0.3316, 0.7726, 0.0843, 0.3117]])


In [52]:
q=b.view(16)
print(q)

tensor([0.6276, 0.9930, 0.2717, 0.6213, 0.5980, 0.1673, 0.1510, 0.6388, 0.1697,
        0.8272, 0.5762, 0.1804, 0.3316, 0.7726, 0.0843, 0.3117])


In [54]:
#pytorch determine the right value if we put -1.
w=b.view((-1,8))
print(w)
print(w.size())

tensor([[0.6276, 0.9930, 0.2717, 0.6213, 0.5980, 0.1673, 0.1510, 0.6388],
        [0.1697, 0.8272, 0.5762, 0.1804, 0.3316, 0.7726, 0.0843, 0.3117]])
torch.Size([2, 8])


# Converting numpy to torch and vice versa

In [60]:
#Tensor to Numpy
k=torch.ones(5)
print(k)
l=k.numpy()
print(l)
print(type(l))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


We have to be careful as if tensor is on CPU and not on GPU then both objects will share the same memory location so that if we change one, we will also change the other.If we change one then the other also gets changed

In [61]:
#Example
k.add_(1)
print(k)
print(l)


tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [78]:
#Numpy to Torch
a=np.ones(5)
print(a)
b = torch.from_numpy(a).to(dtype=torch.float32)
print(b)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


In [79]:
#GPU not connected
a+=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.])


To convert Tensor to numpy, it has to be done always on CPU.

In [82]:
#By default the value is false. When we change it to true, it means later it has to perform gradients.
x=torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
