In [33]:
#Pytorch has "autograd" package which can find all the derivatives
import torch

In [42]:
x=torch.rand(3, requires_grad=True)
print(x)
print(x.dtype)

tensor([0.8385, 0.8267, 0.6974], requires_grad=True)
torch.float32


In [58]:
#Pytorch creates a computational graph
y=x+2
print(y)

tensor([2.8385, 2.8267, 2.6974], grad_fn=<AddBackward0>)


In [59]:
#MulBackward as here our operation is multiplication
z=y*y*2
print(z)

tensor([16.1140, 15.9807, 14.5524], grad_fn=<MulBackward0>)


In [60]:
#z=c.mean()
print(z)
print(z.dtype)

tensor([16.1140, 15.9807, 14.5524], grad_fn=<MulBackward0>)
torch.float32


In [61]:
#backpropagation
#z.backward() #dz/dx(mean value only)
#he calculated gradients are then stored in the grad attribute of the tensor x.
#print(x.grad)

In [62]:
#When not a scalar
#x.grad will contain the gradients of z with respect to x, each element scaled by the corresponding weight from the vector v. The use of weights in backpropagation is a way to assign different importance to different elements in the loss calculation.
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([1.1354e+00, 1.1307e+01, 1.0790e-02])


Preventing Gradient History

In [63]:
#x.requires_grad_(False)
#x.requires_grad_(False)
#print(x)

tensor([0.8385, 0.8267, 0.6974])


In [64]:
#x.detach()
y=x.detach()
print(y)

tensor([0.8385, 0.8267, 0.6974])


In [65]:
#with torch.no_grad():
with torch.no_grad():
    y=x+2
    print(y)
    

tensor([2.8385, 2.8267, 2.6974])


# Dummy Training Example 

In [66]:
weights=torch.ones(4,requires_grad=True)

In [69]:
for epoch in range(2):
    model_output=(weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    weights.grad.zero_()
    

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# Optimization

In [76]:
weights=torch.ones(4,requires_grad=True)

In [77]:
#Stochastic Gradient Descent
optimizer=torch.optim.SGD([weights],lr=0.01)
optimizer.step()
optimizer.zero_grad()